Repository kveola13/FootballPredictionAPI, pull requests merged in 2023-01, with the labels that each got.

#14 Fixed endpoints to use FootballTeamDTO
  FootballPredictionAPI/Controllers/FootballTeamsController.cs
Labels: enhancement

#15 Create dotnet-desktop.yml
  .github/workflows/dotnet-desktop.yml
Labels: enhancement

#19 Fix CreateFootballTeamDto
  FootballPredictionAPI/Controllers/FootballTeamsController.cs
  FootballPredictionAPI/DTOs/CreateFootballTeamDTO.cs
  FootballPredictionAPI/MappingConfig.cs
Labels: enhancement

#30 16 update to add cosmos db
  .github/workflows/FootballPredictionAPI.yml
  FootballPredictionAPI/.config/dotnet-tools.json
  FootballPredictionAPI/Controllers/FootballTeamsController.cs
  FootballPredictionAPI/DTOs/CreateFootballTeamDTO.cs
  FootballPredictionAPI/FootballPredictionAPI.csproj
  FootballPredictionAPI/Interfaces/IFootballRepository.cs
  FootballPredictionAPI/MappingConfig.cs
  FootballPredictionAPI/Models/FootballTeam.cs
  FootballPredictionAPI/Program.cs
  FootballPredictionAPI/Properties/ServiceDependencies/FootballPredictionAPI - Web Deploy/apis1.arm.json
  FootballPredictionAPI/Properties/ServiceDependencies/FootballPredictionAPI - Web Deploy/profile.arm.json
  FootballPredictionAPI/Properties/ServiceDependencies/FootballPredictionAPI - Web Deploy/secrets2.arm.json
  FootballPredictionAPI/Properties/ServiceDependencies/FootballPredictionAPI/apis1.arm.json
  FootballPredictionAPI/Properties/ServiceDependencies/FootballPredictionAPI/cosmosdb1.arm.json
  FootballPredictionAPI/Properties/ServiceDependencies/FootballPredictionAPI/secrets1.arm.json
  FootballPredictionAPI/Properties/serviceDependencies.FootballPredictionAPI - Web Deploy.json
  FootballPredictionAPI/Properties/serviceDependencies.FootballPredictionAPI.json
  FootballPredictionAPI/Properties/serviceDependencies.json
  FootballPredictionAPI/Repositories/FootballRepository.cs
  FootballPredictionAPI/appsettings.Development.json
  FootballPredictionAPI/appsettings.json
Labels: enhancement

#43 37 add testing
  FootballPredictionAPI.sln
  FootballPredictionAPI/Context/FootballTeamContext.cs
  FootballPredictionAPI/Interfaces/IFootballRepository.cs
  FootballPredictionAPI/Program.cs
  FootballPredictionAPI/Repositories/FootballRepository.cs
  FootballPredictionAPITests/FootballPredictionAPITests.csproj
  FootballPredictionAPITests/Repositories/FootballRepositoryTests.cs
Labels: enhancement

#45 quick update to yml files
  .github/workflows/FootballPredictionAPI.yml
  .github/workflows/dotnet-desktop.yml
Labels: enhancement, help wanted

#50 38 add pipelines
  .github/workflows/FootballPredictionAPI.yml
Labels: bug
